import numpy as np
lst = [1, 2, 3, 4,]
arr = np.array([1, 2, 3, 4])
print(type(lst))
print(type(arr))
print("----------------------------------")
a = np.array([1, 2, 3])
b = np.array([5])
c = np.array([4])
d = np.arange(1, 10)
e = np.linspace(1, 10, 5)
print(a,b,c,d,e, sep="\n")
print("----------------------------------")
f = np.array([1,2,3,7,8,9])
g = np.array([4,5,6,1,2,3])
print(f+g)
print(f-g)
print(f*g)
print(f/g)
print(f**2)
print(g**2)
print("----------------------------------")
print("1D array")
ar = np.array([10,20,30,40,50])
print(ar[0])
print(ar[-1])
print(ar[1:4])
print("----------------------------------")
arr = np.array([10,20,30,40,50])
h = np.mean(arr)
i = np.max(arr)
j = np.min(arr)
k = np.std(arr)
print(h,i,j,k, sep="\n")
print("----------------------------------")
l  = np.array([[1,2],[3,4]])
o = np.array([[5,6],[7,8]])
print(l+o)
m = np.sin(0)
n = np.cos(1)
print(m,n, sep="\n")
print("----------------------------------")
